version: "3.8"

services:
  # PostgreSQL Database
  database:
    image: postgres:15
    container_name: todo_database
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432" # Use port 5435 to avoid conflicts
    networks:
      - todo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d todoapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_backend
    environment:
      DATABASE_URL: postgresql://todouser:todopass@database:5432/todoapp
      HOST: 0.0.0.0
      PORT: 8000
    ports:
      - "8001:8000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - todo_network
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo_frontend
    environment:
      REACT_APP_API_URL: http://localhost:8001
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - todo_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

# Named volumes
volumes:
  postgres_data:

# Custom network
networks:
  todo_network:
    driver: bridge
