# Configuration file for the project

artifact_dir: artifacts

data_ingestion:
  root_dir: artifacts
  ingestion_dir: artifacts/data_ingestion
  dataset_location: Datasets

data_validation:
  root_dir: artifacts/data_validation
  dataset_location: artifacts/data_ingestion
  STATUS_FILE: artifacts/data_validation/status.yaml

data_transformation:
  root_dir: artifacts/data_transformation
  dataset_location: artifacts/data_ingestion
  STATUS_FILE: artifacts/data_validation/status.yaml

mariadb_load:
  final_dataset_path: artifacts/data_transformation
  final_dataset_name: transformed_data_final.csv
  table_name: final_dataset

redis_key:
  final_dataset_key: final_dataset_key

model_trainer:
  root_dir: artifacts
  save_model_dir: artifacts/models
  model_name: final_model
  save_train_data_dir: artifacts/model_trainer
  train_dir: artifacts/model_trainer/train
  test_dir: artifacts/model_trainer/test
  train_dataset_name: train_data.csv
  test_dataset_name: test_data.csv
  target_column: FTR
  dataset_name: final_dataset.csv
