# Generated by Django 5.2.1 on 2025-06-07 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=10)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('stadium', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Match date')),
                ('home_team', models.CharField(help_text='Home team name', max_length=100)),
                ('away_team', models.CharField(help_text='Away team name', max_length=100)),
                ('fthg', models.IntegerField(help_text='Full Time Home Goals', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('ftag', models.IntegerField(help_text='Full Time Away Goals', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('ftr', models.CharField(choices=[('H', 'Home Win'), ('A', 'Away Win'), ('D', 'Draw')], help_text='Full Time Result', max_length=1)),
                ('season', models.CharField(help_text='Season in format 2019-20', max_length=10)),
                ('matchweek', models.IntegerField(help_text='Match week number', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(38)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'home_team'],
                'indexes': [models.Index(fields=['date'], name='football_ap_date_5fd15f_idx'), models.Index(fields=['home_team'], name='football_ap_home_te_c2380d_idx'), models.Index(fields=['away_team'], name='football_ap_away_te_595d19_idx'), models.Index(fields=['season'], name='football_ap_season_15f317_idx'), models.Index(fields=['matchweek'], name='football_ap_matchwe_a30251_idx')],
                'unique_together': {('date', 'home_team', 'away_team')},
            },
        ),
    ]
